version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-game-app
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senhasegura
      MYSQL_DATABASE: game
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - game-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-game-app
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: senhasegura
    depends_on:
      - mysql
    networks:
      - game-network

  api:
    build: .
    container_name: space-api
    ports:
      - "3333:3333"
    depends_on:
      - mysql
    networks:
      - game-network
    volumes:
      - .:/app

volumes:
  mysql-data:

networks:
  game-network:
    driver: bridge
